spring:
   datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/spring?useSSL=false&useUnicode=true&characterEncoding=UTF-8
     username: root
     password:

   jpa:
     hibernate:
        ddl-auto:
     show-sql: true